version: "3.1"
services:
  e_mysql:
    image: mysql:8.0
    container_name: e_mysql
    working_dir: /var/www/html
    volumes:
      - ./server_config/mysql/8.0/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      # MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
    command: --lower_case_table_names=2

  e_web:
    build:
      context: ./server_config/web
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    container_name: e_web
    restart: always
    volumes:
      - .:/var/www/html
      - ./server_config/nginx:/etc/nginx/conf.d
      - ./server_config/php/8.2/fpm/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./server_config/php/8.2/fpm/php.ini:/etc/php/8.2/fpm/php.ini
      - ./server_config/web/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "${APP_PORT:-80}:80"
      - "${WS_PORT:-6001}:6001"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
      - "${SSL_PORT:-443}:443"

  e_redis:
    image: 'redis:alpine'
    container_name: e_redis
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './server_config/redis:/data'
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  cloud_e:
    driver: bridge
